# Generated by Django 3.1.3 on 2020-11-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_donations_report_financial_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('mainphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('contents', models.TextField()),
            ],
        ),
    ]
