# Generated by Django 3.1.3 on 2020-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_project_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
