# Generated by Django 3.1.3 on 2020-11-27 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
