# Generated by Django 2.2.6 on 2021-01-09 16:15

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_notice_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Financial',
        ),
        migrations.AddField(
            model_name='donations_report',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donations_report',
            name='contents',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='contents',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='contents',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
